title: zweifeln.org
author: Gero Nagel
url: https://zweifeln.org
description: Zweifeln, Ideen und der Podcast Glaube mit Zweifeln
permalink: /:year/:title/
podcast: Glaube mit Zweifeln
podcast_url: /glaube
podcast_description: Was genau ist Glaube?
markdown: kramdown
plugins: 
  - jekyll-paginate
paginate: 10
